version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  test_all:
    executor: node-executor
    steps:
      - checkout
      - run: yarn
      - run: |
          yarn lint && \
          yarn format:check && \
          yarn test && \
          yarn test:cov && \
          yarn test:e2e

  docker_build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud config set project $GCLOUD_PROJECT
          gcloud auth configure-docker
      - run: |
          docker build -t gcr.io/$GCLOUD_PROJECT/hello-world:latest .
          docker push gcr.io/$GCLOUD_PROJECT/hello-world:latest

# Workflows: Farklı senaryolar için iş akışları tanımlama
workflows:
  version: 2
  # Pull request oluşturulduğunda tetiklenecek iş akışı (Deploy işlemi yapılacak)
  deploy_on_pull_request:
    jobs:
      - docker_build:
          filters:
            branches:
              ignore:
                - develop
                - main # PR oluşturulunca deploy yapılacak

  # Pull request onaylandığında veya doğrudan develop branch'ına commit yapıldığında tetiklenecek iş akışı (Test işlemleri yapılacak)
  test_on_commit_or_merge:
    jobs:
      - test_all:
          filters:
            branches:
              only:
                - develop