version: 2.1

jobs:
  production_deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate to Google Cloud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT
            gcloud auth configure-docker
            gcloud container clusters get-credentials atolye15 --zone europe-west3-a --project $GCLOUD_PROJECT
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f k8s/production/deployment.yaml
            kubectl apply -f k8s/production/service.yaml
            kubectl rollout restart deployment hello-world-deployment -n production

  send_email:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Send Email Notification via SendGrid
          command: |
            curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header 'Authorization: Bearer $SENDGRID_API_KEY' \
            --header 'Content-Type: application/json' \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "ibrahimtalhaasan@gmail.com"
                    }
                  ],
                  "subject": "Prod Deployment Notification"
                }
              ],
              "from": {
                "email": "talha.asan@outlook.com"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "Prod Deployment completed successfully!"
                }
              ]
            }'

  check_source_branch:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check if PR is to master
          command: |
            if [[ -z "$CIRCLE_PULL_REQUEST" ]]; then
              echo "This is not a PR. Skipping check."
              exit 0
            elif [[ "$CIRCLE_BRANCH" == "master" ]]; then
              echo "This is a PR to master. Proceeding with production deployment steps."
              exit 0
            else
              echo "Not a PR to master. Skipping production deployment steps."
              exit 1
            fi

workflows:
  version: 2
  deploy_on_pr_from_develop_to_master:
    jobs:
      - check_source_branch:
          filters:
            branches:
              only:
                - master  # PR hedefi master olduğunda çalışır
      - production_deploy:
          requires:
            - check_source_branch
          filters:
            branches:
              only:
                - master  # PR master'a açıldığında tetiklenir ve deploy yapılır
      - send_email:
          requires:
            - production_deploy
          filters:
            branches:
              only:
                - master  # PR master'a açıldığında tetiklenir ve email gönderilir
